import { test, expect } from '@playwright/test';

test('member', async ({ page }) => {
  await page.goto('http://203.158.198.234/cameraman/index.php');
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('menuitem', { name: 'สมัครสมาชิก ▾' }).click();
  await page.getByRole('menuitem', { name: 'สมาชิก', exact: true }).click();
  await page.getByRole('textbox', { name: 'ชื่อ-นามสกุล' }).click();
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'ชื่อ-นามสกุล' }).fill('นายสมบูน บุนมา');
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'อีเมล (ภาษาอังกฤษเท่านั้น)' }).fill('การทำ@gma');
  await page.getByRole('textbox', { name: 'อีเมล (ภาษาอังกฤษเท่านั้น)' }).click();
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'อีเมล (ภาษาอังกฤษเท่านั้น)' }).click();
  await page.getByRole('textbox', { name: 'อีเมล (ภาษาอังกฤษเท่านั้น)' }).fill('ningwy123@gmail.com');
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (อย่างน้อย 6' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (อย่างน้อย 6' }).fill('12345678');
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'ยืนยันรหัสผ่าน' }).fill('12345678');
  await page.getByRole('button', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).fill('ningwy@gmail.com');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('12345678');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).fill('ningwy123@gmail.com');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('12345678');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'ไปที่ Dashboard' }).click();
  await page.getByRole('link', { name: 'แก้ไขข้อมูล', exact: true }).click();
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('0979961122');
  await page.getByRole('button', { name: '💾 บันทึกการเปลี่ยนแปลง' }).click();
  await page.getByRole('button', { name: 'บันทึกเลย' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('link', { name: 'แก้ไขข้อมูล' }).click();
  await page.getByRole('button', { name: '💾 บันทึกการเปลี่ยนแปลง' }).click();
  await page.getByRole('button', { name: 'บันทึกเลย' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'โปรไฟล์ โมดิฟาย สุรินทร์ อีเมล: modify.oa@hotmail.com เบอร์โทร: 0889338788' }).click();
  await page.getByRole('link', { name: '📖 ดูตารางงาน' }).click();
  await page.getByRole('link', { name: '📅 ไปจอง' }).click();
  await page.getByRole('button', { name: 'ฉันเข้าใจ' }).click();
  await page.getByRole('textbox', { name: 'วันที่จอง' }).fill('2025-10-10');
  await page.getByRole('textbox', { name: 'เวลา' }).click();
  await page.getByRole('textbox', { name: 'เวลา' }).fill('00:00');
  await page.getByRole('textbox', { name: 'สถานที่' }).click();
  await page.getByRole('textbox', { name: 'สถานที่' }).fill('บ้านสวย');
  await page.getByLabel('ประเภทงาน').selectOption('อีเวนต์');
  await page.getByRole('textbox', { name: 'ความต้องการเพิ่มเติม' }).click();
  await page.getByRole('textbox', { name: 'ความต้องการเพิ่มเติม' }).fill('งานสบายๆ');
  await page.getByRole('button', { name: '💾 ยืนยันการจอง' }).click();
  await page.getByRole('button', { name: 'ฉันเข้าใจ' }).click();
  await page.getByRole('button', { name: '💾 ยืนยันการจอง' }).click();
  await page.getByRole('textbox', { name: 'วันที่จอง' }).fill('2025-10-17');
  await page.getByRole('button', { name: '💾 ยืนยันการจอง' }).click();
  await page.getByRole('textbox', { name: 'เวลา' }).click();
  await page.getByRole('textbox', { name: 'เวลา' }).fill('00:59');
  await page.getByRole('textbox', { name: 'สถานที่' }).click();
  await page.getByRole('button', { name: '💾 ยืนยันการจอง' }).click();
  await page.getByRole('textbox', { name: 'เวลา' }).click();
  await page.getByRole('textbox', { name: 'เวลา' }).fill('10:00');
  await page.getByRole('textbox', { name: 'สถานที่' }).click();
  await page.getByRole('button', { name: '💾 ยืนยันการจอง' }).click();
  await page.getByRole('button', { name: 'ฉันเข้าใจ' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูคะแนนช่างภาพ ⭐' }).click();
  await page.getByText('Chokniti coo Talaynoi').click();
  await page.getByText('Chokniti coo Talaynoi').click();
  await page.getByRole('link', { name: 'สถานที่แนะนำ 📍' }).click();
  await page.getByRole('link', { name: 'อัปโหลดหลักฐานโอนเงิน' }).click();
  await page.getByRole('link', { name: 'ติดต่อผู้ดูแลระบบ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามการจอง' }).click();
  await page.getByRole('button', { name: 'ส่งข้อความ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามการจอง' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามการจอง' }).fill('งานไม่มา');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดที่ต้องการติดต่อ' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดที่ต้องการติดต่อ' }).fill('คนถ่ายไม่มา');
  await page.getByRole('button', { name: 'ส่งข้อความ' }).click();
  await page.getByRole('link', { name: 'ออกจากระบบ' }).click();
});


test('photographer login and workflow', async ({ page, context }) => {
  // เข้าหน้าเว็บ
await page.goto('http://203.158.198.234/cameraman/index.php');
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('menuitem', { name: 'เข้าสู่ระบบ ▾' }).click();
  await page.getByRole('menuitem', { name: 'ช่างภาพ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).fill('ning107@gmail.com');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('12345678');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'ไปที่แดชบอร์ด' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('row', { name: '24/09/2025 15:00' }).getByRole('combobox').selectOption('ยืนยันแล้ว');
  await page.getByRole('row', { name: '24/09/2025 15:00' }).getByRole('button').click();
  await page.locator('select[name="status"]').selectOption('รอดำเนินการ');
  await page.getByRole('button', { name: 'ค้นหา' }).click();
  await page.getByRole('row', { name: '21/09/2025 10:00' }).getByRole('link').click();
  await page.getByRole('cell', { name: '11 ＋เพิ่มงาน' }).getByRole('link').click();
  await page.locator('input[name="job_time"]').click();
  await page.locator('input[name="job_time"]').fill('10:00');
  await page.getByRole('textbox', { name: 'เช่น วัดพระแก้ว, สตูดิโอ A' }).click();
  await page.getByRole('textbox', { name: 'เช่น วัดพระแก้ว, สตูดิโอ A' }).fill('บ้านมา');
  await page.locator('select[name="status"]').selectOption('ยืนยันแล้ว');
  await page.getByRole('textbox', { name: 'รายละเอียดเพิ่มเติม' }).click();
  await page.getByRole('textbox', { name: 'รายละเอียดเพิ่มเติม' }).fill('งาน');
  await page.getByRole('button', { name: 'บันทึกงาน' }).click();
  await page.getByText('ตกลง').click();
  await page.getByTitle(':00 บ้านมา ยืนยันแล้ว').getByRole('link').click();
  await page.locator('select[name="status"]').selectOption('เสร็จสิ้น');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByText('ตกลง').click();
  await page.getByRole('cell', { name: '11 ＋เพิ่มงาน 10:00' }).getByRole('button').click();
  await page.getByText('ลบงาน', { exact: true }).click();
  await page.getByText('ตกลง').click();
  await page.getByRole('link', { name: 'ข้อมูลทั่วไป' }).click();
  await page.locator('.photo-card > img').first().click();
  await page.getByRole('button', { name: 'ถัดไป' }).click();
  await page.getByRole('button', { name: 'ถัดไป' }).click();
  await page.getByRole('button', { name: 'ปิด' }).click();
  await page.getByRole('link', { name: 'ส่งงานลูกค้า' }).click();
  await page.getByRole('textbox', { name: 'เช่น https://drive.google.com/' }).click();
  await page.getByRole('textbox', { name: 'เช่น https://drive.google.com/' }).fill('https://www.google.com');
  await page.getByRole('textbox', { name: 'หัวเรื่อง (เช่น ส่งงานไฟนอล)' }).click();
  await page.getByRole('textbox', { name: 'หัวเรื่อง (เช่น ส่งงานไฟนอล)' }).fill('งาน');
  await page.getByRole('textbox', { name: 'โน้ตเพิ่มเติม (ถ้ามี)' }).click();
  await page.getByRole('textbox', { name: 'โน้ตเพิ่มเติม (ถ้ามี)' }).fill('งาน');
  await page.getByRole('button', { name: 'บันทึกลิงก์' }).click();
  await page.getByText('ตกลง').click();
  await page.getByRole('link', { name: 'ติดต่อผู้ดูแลระบบ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามงาน' }).click();
  await page.getByRole('button', { name: 'ส่งข้อความ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามงาน' }).click();
  await page.getByRole('textbox', { name: 'เช่น ปัญหาการใช้งาน, แจ้งบั๊ก, สอบถามงาน' }).fill('งาน');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดที่ต้องการติดต่อ' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดที่ต้องการติดต่อ' }).fill('5555');
  await page.getByRole('button', { name: 'ส่งข้อความ' }).click();
  await page.getByRole('link', { name: 'การจองคิว' }).click();
  await page.getByRole('row', { name: '#72 21/09/2025 10:00' }).getByRole('link').click();
  await page.locator('section').filter({ hasText: 'แก้ไขงาน #72' }).getByRole('combobox').selectOption('ยืนยันแล้ว');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('link', { name: 'เพิ่มสถานที่แนะนำ' }).click();
  await page.getByRole('button', { name: 'บันทึก' }).click();
  await page.locator('input[name="location_name"]').fill('บ้าน');
  await page.locator('input[name="address"]').click();
  await page.locator('input[name="address"]').fill('บ้านนาดี');
  await page.locator('textarea[name="description"]').click();
  await page.locator('textarea[name="description"]').fill('5555');
  await page.getByRole('button', { name: 'บันทึก' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('link', { name: 'การมัดจำ' }).click();
  await page.getByRole('combobox').selectOption('all');
  await page.getByRole('button', { name: 'ค้นหา' }).click();
  await page.getByRole('link', { name: 'แก้ไขข้อมูล' }).click();
  await page.locator('input[name="last_name"]').click();
  await page.locator('input[name="last_name"]').fill('');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.locator('input[name="last_name"]').click();
  await page.locator('input[name="last_name"]').fill('เสียงดีดี');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.locator('.del-form > button').first().click();
  await page.getByLabel('ยืนยันการลบรูปภาพ').getByRole('button', { name: 'ลบ' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('link', { name: 'ออกจากระบบ' }).click();

});

test('Admin', async ({ page }) => {
  await page.goto('http://203.158.198.234/cameraman/index.php');
  await page.getByRole('link', { name: 'เข้าสู่ระบบ ▾' }).click();
  await page.getByRole('link', { name: 'ผู้ดูแลระบบ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).fill('nning16999@gmail.com');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('12345678');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'ไปที่แดชบอร์ด' }).click();
  await page.getByRole('link', { name: 'สมาชิก' }).click();
  await page.getByRole('row', { name: '2015 นายสมบูน บุนมา ningwy123' }).getByRole('link').click();
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('0979961222');
  await page.getByRole('button', { name: 'บันทึก' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.locator('#topMenu').getByRole('link', { name: 'ช่างภาพ', exact: true }).click();
  await page.getByRole('row', { name: '39 profile Chokniti coo' }).getByRole('link').click();
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('0979364444');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.locator('#topMenu').getByRole('link', { name: 'การจอง' }).click();
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('select[name="photographer_id"]').selectOption('39');
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('select[name="user_id"]').selectOption('46');
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('input[name="job_date"]').fill('2025-10-12');
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('input[name="job_time"]').click();
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('input[name="job_time"]').fill('11:00');
  await page.getByRole('textbox', { name: 'เช่น CentralWorld, กรุงเทพฯ' }).click();
  await page.getByRole('textbox', { name: 'เช่น CentralWorld, กรุงเทพฯ' }).fill('บ้าน');
  await page.locator('form').filter({ hasText: 'ช่างภาพ — เลือกช่างภาพ —' }).locator('select[name="status"]').selectOption('ยืนยันแล้ว');
  await page.getByRole('button', { name: 'เพิ่มการจอง' }).click();
  await page.getByRole('button', { name: 'ตกลง' }).click();
  await page.getByRole('textbox', { name: 'เช่น Bangkok, Studio A' }).click();
  await page.getByRole('textbox', { name: 'เช่น Bangkok, Studio A' }).fill('บ้าน');
  await page.getByRole('button', { name: 'กรอง' }).click();
  await page.getByRole('row', { name: '188 2025-10-12 11:00 บ้าน' }).locator('summary').click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('link', { name: 'ข้อความช่างภาพ' }).click();
  await page.getByRole('link', { name: 'งาน', exact: true }).first().click();
  await page.getByRole('textbox', { name: 'พิมพ์ข้อความตอบกลับ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์ข้อความตอบกลับ' }).fill('5555');
  await page.getByRole('button', { name: 'ส่งคำตอบ' }).click();
  await page.locator('#topMenu').getByRole('link', { name: 'ข้อความลูกค้า' }).click();
  await page.getByRole('link', { name: 'งานไม่มา' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์ข้อความตอบกลับ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์ข้อความตอบกลับ' }).fill('55555555');
  await page.getByRole('button', { name: 'ส่งคำตอบ' }).click();
  await page.locator('#topMenu').getByRole('link', { name: 'ประวัติ' }).click();
  await page.getByRole('link', { name: 'สถานที่' }).click();
  await page.locator('input[name="location_name"]').click();
  await page.locator('input[name="location_name"]').fill('บ้าน');
  await page.getByPlaceholder('ใส่ user_id หรือเว้นว่าง').click();
  await page.getByPlaceholder('ใส่ user_id หรือเว้นว่าง').fill('30');
  await page.locator('input[name="address"]').click();
  await page.locator('input[name="address"]').fill('บ้าน');
  await page.getByRole('textbox', { name: 'เช่น 34a7f67a350b' }).click();
  await page.locator('textarea[name="description"]').click();
  await page.locator('textarea[name="description"]').fill('บ้าน');
  await page.getByRole('button', { name: 'บันทึก' }).click();
  await page.getByRole('row', { name: 'บ้าน บ้าน บ้าน - #30 2025-10-' }).getByRole('button').click();
  await page.getByRole('button', { name: 'ลบเลย' }).click();
  await page.getByRole('link', { name: 'ประวัติ' }).click();
  await page.getByRole('link', { name: 'ข้อความลูกค้า' }).click();
  await page.locator('#topMenu').getByRole('link', { name: 'สถานที่' }).click();
  await page.getByRole('link', { name: 'ออกจากระบบ' }).click();
});

test('General users', async ({ page }) => {
  await page.goto('http://203.158.198.234/cameraman/index.php');
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'รูปโปรไฟล์ Chokniti coo' }).click();
  await page.getByRole('link', { name: '📖 ดูตารางงาน' }).click();
  await page.getByRole('link', { name: '📅 ไปจอง' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'รูปโปรไฟล์ Chokniti coo' }).click();
  await page.getByRole('link', { name: '⭐ ดูรีวิวของช่างภาพนี้' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'รูปโปรไฟล์ Chokniti coo' }).click();
  await page.getByRole('link', { name: '📍สถานที่แนะนำ' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'รูปโปรไฟล์ Chokniti coo' }).click();
  await page.getByRole('link', { name: '📅 จองช่างภาพนี้' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
  await page.getByRole('link', { name: 'ดูรายชื่อช่างภาพ' }).click();
  await page.getByRole('link', { name: 'รูปโปรไฟล์ Chokniti coo' }).click();
  await page.getByRole('link', { name: 'งานแต่ง' }).first().click();
  await page.getByRole('button', { name: 'ถัดไป »' }).click();
  await page.getByRole('button', { name: 'ถัดไป »' }).click();
  await page.getByRole('button', { name: 'ปิด ✕' }).click();
  await page.getByRole('link', { name: 'หน้าแรก' }).click();
});
// test('facebook' , async({ page }) =>{
//     await page.goto('https://www.facebook.com/');
    
//     //Locator การระบุตำแหน่ง getByRole
//    // await page.getByRole('button', { name: 'Log in'}).click();
//    // await page.getByRole('button', { name: 'Create new account'}).click();
//  //   await page.getByRole('textbox', { name: 'Email address or phone number'}).click();
//       await page.getByRole('textbox', { name: 'Email address or phone number'}).fill("0631966902");
//       await page.getByRole('textbox', { name: 'Password'}).fill("12345");
      

// });
// test("facebook_register", async({ page }) =>{
//     await page.goto("https://www.facebook.com/");
//     await page.getByRole("button",{name:"Create new account"}).click();
//     await page.getByRole('textbox', { name: 'First name'}).fill("porntip");
//     await page.getByRole('textbox', { name: 'Surname'}).fill("poonsap");
//     await page.getByRole('textbox', { name: 'Mobile number or email address'}).fill("0631966902");
//     await page.getByRole('textbox', { name: 'New password'}).fill("12345");
//     await page.getByLabel("Day").selectOption("10");
//     await page.getByLabel("Month").selectOption("6");
//     await page.getByLabel("Year").selectOption("1999");
//     await page.getByLabel("Female").check();
//     await page.getByRole("button",{name:"Sign Up"}).click();
//   });

//   test('computer', async ({ page }) => {
//       await page.goto('https://computer.surin.rmuti.ac.th/sc/fornend/');
//       await page.getByRole('link', { name: 'สมัครสมาชิก' }).click();
//       await page.getByRole('textbox', { name: 'ชื่อ',exact:true}).fill("NING");
//       await page.getByRole('textbox', { name: 'นามสกุล'}).fill("NING");
//       await page.getByRole('textbox', { name: 'ชื่อผู้ใช้',exact:true}).fill("NING");
//       await page.getByRole('textbox', { name: 'รหัสผ่าน' ,exact:true}).fill("123456");
//       await page.getByRole('textbox', { name: 'ยืนยันรหัสผ่าน' ,exact:true}).fill("123456");
//       await page.getByRole('textbox', { name: 'เบอร์โทรศัพท์'}).fill("0957160117");
//       await page.getByRole('textbox', { name: 'อีเมล'}).fill("tarairat@rmuti.ac.th");
//       await page.getByRole('button', { name: ' สมัครสมาชิก' }).click();
      
//   });
 
//     test('login', async ({ page }) => {
//       await page.goto('https://computer.surin.rmuti.ac.th/sc/fornend/');
//   await page.getByRole('link', { name: 'เข้าสู่ระบบ' }).click();
//   await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
//   await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('ning');
//   await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
//   await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
//   await page.getByRole('button', { name: ' เข้าสู่ระบบ' }).click();
//         await expect(page.getByRole('heading', { name: 'กลุ่มวิชาเรียนทั้งหมด' })).toBeVisible();
//          await expect(page.getByRole('heading', { name: 'คอร์สเรียนทั้งหมด' })).toBeVisible();
//     });
    
//  test('ig', async ({ page }) => {
//         await page.goto('https://www.instagram.com/');
//         await page.getByRole('textbox', { name: 'Phone number, username, or email' }).fill("ning");                 
//         await page.getByRole('textbox', { name: 'Password' }).fill("12345");
//         await page.getByRole('button', { name: 'Log In' }).click();
//         await expect(page).toHaveURL(/instagram\.com/);
//           await page.getByRole('link', { name: 'ลืมรหัสผ่านใช่ไหม' }).click();
//     await page.getByRole('textbox', { name: 'หมายเลขโทรศัพท์มือถือ ชื่อผู้ใช้ หรืออีเมล' }).click();
//     await page.getByRole('textbox', { name: 'หมายเลขโทรศัพท์มือถือ ชื่อผู้ใช้ หรืออีเมล' }).fill('0979869972');
//     await page.getByRole('button', { name: 'ดำเนินการต่อ' }).click();
//        });